- name: backlog
  color: '16774c'
- name: bug:confirmed
  color: 'fc1423'
- name: bug:unverified
  color: 'f9d0c4'
- name: chore
  color: 'ffffff'
- name: ci
  color: '0075ca'
- name: dependencies
  color: '276bd1'
- name: documentation
  color: '0075ca'
- name: duplicate
  color: 'bac4c2'
- name: feature
  color: 'ffff00'
- name: has PR
  color: '4b1f8e'
- name: in review
  color: 'aed5fc'
- name: needs rebase & merge
  color: '24853c'
- name: packages:eslint-config
  color: 'fbca04'
- name: packages:eslint-plugin-result
  color: 'fbca04'
- name: packages:fetch
  color: 'fbca04'
- name: packages:node-utilities
  color: 'fbca04'
- name: packages:prettier-config
  color: 'fbca04'
- name: packages:result
  color: 'fbca04'
- name: packages:ts-config
  color: 'fbca04'
- name: performance
  color: '80c042'
- name: priority:critical
  color: 'b60205'
- name: priority:high
  color: 'fc1423'
- name: priority:low
  color: 'bac60e'
- name: priority:lowest
  color: '5a7532'
- name: refactor
  color: '1d637f'
- name: regression
  color: 'ea8785'
- name: tests
  color: 'f06dff'
- name: typings
  color: '80c042'
