name: Continuous Integration

on:
  push:
    branches:
      - main
      - stable
  pull_request:

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"
      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          # registry-url: 'https://npm.pkg.github.com'
          # scope: '@shotcowboystyle'
      - name: Install Dependencies
        uses: ./.github/actions/install-deps
      - name: Check for no duplicate dependencies
        run: pnpm dedupe --check

      - name: Build
        run: pnpm build

      - name: Check TypeScript
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint:check

  BuildingAndTesting:
    name: Building and Testing with node v${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [16, 18, 19]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Use Node.js v{{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://npm.pkg.github.com'
          # scope: '@shotcowboystyle'
      - name: Install Dependencies
        uses: ./.github/actions/install-deps
      - name: Build Code
        run: pnpm build
      - name: Run tests
        run: pnpm test
      - name: Codecov Upload ${{ matrix.node }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/cobertura-coverage.xml
          flags: ${{ matrix.node }}
          fail_ci_if_error: true
