name: Automatic Label Sync

on:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  label_sync:
    permissions:
      contents: read
      pull-requests: write
    name: Automatic Label Synchronization
    runs-on: ubuntu-latest
    if: github.repository_owner == 'shotcowboystyle'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Run Label Sync
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
